# -*- coding: utf-8 -*-
"""Ascendeum Round 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YsmVp0xKqC4QCh8CYBtfjx5kOUIaxKI
"""

import numpy as np

a=np.arange(1,17).reshape(4,4)
a

# Method 1:
a=np.arange(1,17).reshape(4,4)
print('initial array: ')
print(a)

a[1][3]=a[1][0]
a[2][3] =a[1][1]
a[3][3]=a[1][2]
a[3][2]=a[3][3]+1
a[3][1]=a[2][0]
a[3][0]=a[2][1]
a[2][0]=a[3][0]+1
a[1][0]=a[2][0]+1
a[1][1]=a[1][0]+1
a[1][2]=a[1][1]+1
a[2][2]=a[1][2]+1
a[2][1]=a[2][2]+1
print('final_array')
print(a)

# Method 2: using loop

arr=np.arange(1,17).reshape(4,4)
arr
num=4
n=num**2
top=0
right=num-1
bottom=0
left=num-1
k=0

for col in range(len(arr[0])):
    print(arr[0][col],end=' ')